FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as build-env
WORKDIR /app

COPY src/. .
WORKDIR /app/ArbitralSystem.Distributor.MarketInfoAggregatorService

RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:3.1
WORKDIR /app
COPY --from=build-env /app/ArbitralSystem.Distributor.MarketInfoAggregatorService/out .

ENTRYPOINT ["dotnet", "ArbitralSystem.Distributor.MarketInfoAggregatorService.dll"]