FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as build-env
WORKDIR /app

COPY src/. .
WORKDIR /app/ArbitralSystem.Storage.FakeMarketInfoStorageService

RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:3.1
WORKDIR /app
COPY --from=build-env /app/ArbitralSystem.Storage.FakeMarketInfoStorageService/out .

ENTRYPOINT ["dotnet", "ArbitralSystem.Storage.FakeMarketInfoStorageService.dll"]