// <auto-generated />
using System;
using ArbitralSystem.PublicMarketInfoService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArbitralSystem.PublicMarketInfoService.Persistence.Migrations
{
    [DbContext(typeof(PublicMarketInfoBdContext))]
    [Migration("20201123213907_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArbitralSystem.PublicMarketInfoService.Persistence.Entities.PairInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<byte>("Exchange")
                        .HasColumnType("tinyint");

                    b.Property<string>("ExchangePairName")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("UnificatedPairName")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("UtcCreatedAt")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("UtcDelistedAt")
                        .HasColumnType("smalldatetime");

                    b.HasKey("Id");

                    b.HasIndex("ExchangePairName", "Exchange", "UtcDelistedAt")
                        .IsUnique()
                        .HasFilter("[ExchangePairName] IS NOT NULL AND [UtcDelistedAt] IS NOT NULL");

                    b.ToTable("PairInfos");
                });

            modelBuilder.Entity("ArbitralSystem.PublicMarketInfoService.Persistence.Entities.PairPrice", b =>
                {
                    b.Property<byte>("Exchange")
                        .HasColumnType("tinyint");

                    b.Property<string>("ExchangePairName")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasMaxLength(12);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(19,9)");

                    b.Property<DateTime>("UtcDate")
                        .HasColumnType("smalldatetime");

                    b.ToTable("PairPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
