// <auto-generated />
using System;
using ArbitralSystem.PublicMarketInfoService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArbitralSystem.PublicMarketInfoService.Persistence.Migrations
{
    [DbContext(typeof(PublicMarketInfoBdContext))]
    partial class PublicMarketInfoBdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArbitralSystem.PublicMarketInfoService.Persistence.Entities.PairInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DelistedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("varchar(900)")
                        .IsUnicode(false);

                    b.Property<string>("ExchangePairName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QuoteCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnificatedPairName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExchangePairName", "Exchange", "DelistedAt")
                        .IsUnique()
                        .HasFilter("[ExchangePairName] IS NOT NULL AND [DelistedAt] IS NOT NULL");

                    b.ToTable("PairInfos");
                });

            modelBuilder.Entity("ArbitralSystem.PublicMarketInfoService.Persistence.Entities.PairPrice", b =>
                {
                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Exchange")
                        .HasColumnType("int");

                    b.Property<string>("ExchangePairName")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasMaxLength(12);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(19,9)");

                    b.ToTable("PairPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
